/**
 * @file app.config.ts
 * @description Per-game visual identity. Generated by tools/propagate-theme.js.
 * Edit the source script and re-run to update.
 */
export const APP_CONFIG = {
  name: "Qui Est-Ce ?",
  primary: "#F97316",
  secondary: "#9A3412",
  splash: {
    glow: "rgba(154,52,18,0.6)",
    sallyGlow: "rgba(249,115,22,0.8)",
    pillBorder: "rgba(249,115,22,0.5)",
    pillBg: "rgba(154,52,18,0.15)",
    pillText: "#FED7AA",
    suit: "?",
    suit2: "!",
  },
  slides: {
    slide2: { tint: ["rgba(249,115,22,0.55)","rgba(154,52,18,0.7)","rgba(40,15,5,0.95)"], variant: "fan" },
    slide3: { tint: ["rgba(251,146,60,0.45)","rgba(124,45,18,0.85)","rgba(40,15,5,0.95)"], variant: "spread" },
    slide4: { tint: ["rgba(168,85,247,0.45)","rgba(249,115,22,0.7)","rgba(40,15,5,0.95)"], variant: "scattered" },
  },
} as const;

export type SlideVariant = 'fan' | 'scattered' | 'spread' | 'grid';
