/**
 * @file game/[roomCode].tsx
 * @description Game screen for quiestceEngine. Features:
 *   - Real engine logic (deck, rules, scoring)
 *   - Online sync via Socket.IO /game namespace
 *   - AnimatedCard + haptic feedback
 *   - Player avatars, phase banner, action hints, quit confirm, winner modal
 *
 * Generated by tools/generate-game-screens.js — re-run after editing the
 * script to regenerate, or edit freely if you want game-specific UI.
 */
import React, { useReducer, useEffect, useState, useCallback, useRef } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Alert,
  Pressable,
  Modal,
  Animated,
  Easing,
} from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import { useTranslation } from 'react-i18next';
import * as Haptics from 'expo-haptics';
import { io, Socket } from 'socket.io-client';
import AppHeader from '../../src/components/AppHeader';
import AnimatedCard from '../../src/components/AnimatedCard';
import { useTheme } from '../../src/contexts/AppProviders';
import { logger } from '../../src/utils/logger';
import { APP_CONFIG } from '../../src/config/app.config';
import { SOCKET_URL } from '../../shared/api';
import * as Engine from '../../src/game/quiestceEngine';

const log = logger.scoped('GameScreen');
const ME = 'p1';
const BOT_THINK_MS = 1200;

// Reusable presentational sub-components  ──────────────────────────────
function PhaseBanner({ phase, current, isMyTurn, winner, palette }: any) {
  const text = winner
    ? `🏆 ${winner.name ?? winner.winnerId ?? 'Fin'}`
    : isMyTurn
      ? '✋ À votre tour'
      : `⏳ ${current?.name ?? 'Bot'} joue…`;
  const bg = winner ? '#10B981' : isMyTurn ? APP_CONFIG.primary : 'rgba(255,255,255,0.1)';
  return (
    <View style={[styles.banner, { backgroundColor: bg, borderColor: palette.border }]}>
      <Text style={styles.bannerText}>{text}</Text>
      {phase && !winner && <Text style={styles.bannerPhase}>Phase : {phase}</Text>}
    </View>
  );
}

function AvatarRow({ players, currentId, palette }: any) {
  return (
    <View style={styles.avatarRow}>
      {players?.map((p: any) => {
        const isActive = p.id === currentId;
        return (
          <View key={p.id} style={[styles.avatarBox, isActive && { borderColor: APP_CONFIG.primary, borderWidth: 2 }]}>
            <View style={[styles.avatar, { backgroundColor: isActive ? APP_CONFIG.primary : APP_CONFIG.secondary }]}>
              <Text style={styles.avatarEmoji}>{p.isBot ? '🤖' : '👤'}</Text>
            </View>
            <Text style={[styles.avatarName, { color: palette.text }]} numberOfLines={1}>
              {p.name}
            </Text>
            <View style={styles.avatarStats}>
              <Text style={[styles.avatarScore, { color: APP_CONFIG.primary }]}>
                {p.score ?? p.chips ?? p.pairs ?? p.pairsCount ?? (p.hand?.length ?? 0)}
              </Text>
              {p.folded && <Text style={styles.avatarFold}>fold</Text>}
            </View>
          </View>
        );
      })}
    </View>
  );
}

function HelpChip({ palette, text }: any) {
  return (
    <View style={[styles.helpChip, { borderColor: palette.border }]}>
      <Ionicons name="information-circle-outline" size={14} color={palette.textSecondary} />
      <Text style={[styles.helpText, { color: palette.textSecondary }]}>{text}</Text>
    </View>
  );
}

function MoveLog({ entries, palette }: any) {
  if (!entries || entries.length === 0) return null;
  return (
    <View style={[styles.log, { borderColor: palette.border }]}>
      <Text style={[styles.logTitle, { color: palette.textSecondary }]}>📜 Derniers coups</Text>
      {entries.slice(-5).reverse().map((e: any, i: number) => (
        <Text key={i} style={[styles.logRow, { color: palette.text }]} numberOfLines={1}>
          {e.icon ?? '•'} <Text style={{ color: palette.textSecondary }}>{e.who}</Text> {e.what}
        </Text>
      ))}
    </View>
  );
}

function FeedbackToast({ message, visible, color }: any) {
  const opacity = useRef(new Animated.Value(0)).current;
  useEffect(() => {
    if (visible) {
      Animated.sequence([
        Animated.timing(opacity, { toValue: 1, duration: 180, useNativeDriver: true }),
        Animated.delay(900),
        Animated.timing(opacity, { toValue: 0, duration: 280, useNativeDriver: true }),
      ]).start();
    }
  }, [visible, message]);
  return (
    <Animated.View pointerEvents="none" style={[styles.toast, { opacity, backgroundColor: color ?? APP_CONFIG.primary }]}>
      <Text style={styles.toastText}>{message}</Text>
    </Animated.View>
  );
}

function WinnerModal({ visible, winner, onQuit, onAgain, palette }: any) {
  return (
    <Modal visible={visible} transparent animationType="fade">
      <View style={styles.modalBackdrop}>
        <LinearGradient colors={['#0A0A1A', APP_CONFIG.secondary]} style={[styles.modalCard, { borderColor: APP_CONFIG.primary }]}>
          <Text style={styles.modalEmoji}>🏆</Text>
          <Text style={styles.modalTitle}>{winner?.name ?? winner?.winnerId ?? 'Bravo !'}</Text>
          <Text style={[styles.modalSub, { color: palette.textSecondary }]}>{APP_CONFIG.name}</Text>
          <View style={{ flexDirection: 'row', gap: 12, marginTop: 20 }}>
            <TouchableOpacity onPress={onAgain} style={[styles.modalBtn, { backgroundColor: APP_CONFIG.primary }]}>
              <Text style={styles.modalBtnText}>🔄 Rejouer</Text>
            </TouchableOpacity>
            <TouchableOpacity onPress={onQuit} style={[styles.modalBtn, { backgroundColor: 'rgba(255,255,255,0.15)' }]}>
              <Text style={styles.modalBtnText}>Quitter</Text>
            </TouchableOpacity>
          </View>
        </LinearGradient>
      </View>
    </Modal>
  );
}

// Shared base styles — extended per game-kind below
const styles = StyleSheet.create({
  banner: {
    padding: 14, borderRadius: 14, alignItems: 'center', borderWidth: 1, marginBottom: 10,
  },
  bannerText: { color: '#fff', fontSize: 15, fontFamily: 'Inter-Bold' },
  bannerPhase: { color: 'rgba(255,255,255,0.85)', fontSize: 11, fontFamily: 'Inter-SemiBold', marginTop: 3 },
  avatarRow: {
    flexDirection: 'row', justifyContent: 'space-around', marginBottom: 12,
    paddingVertical: 10, paddingHorizontal: 6,
    backgroundColor: 'rgba(255,255,255,0.03)', borderRadius: 14,
  },
  avatarBox: { alignItems: 'center', minWidth: 60, padding: 4, borderRadius: 12 },
  avatar: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center' },
  avatarEmoji: { fontSize: 18 },
  avatarName: { fontSize: 11, fontFamily: 'Inter-SemiBold', marginTop: 4, maxWidth: 60 },
  avatarStats: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 2 },
  avatarScore: { fontSize: 13, fontFamily: 'Inter-Black' },
  avatarFold: { fontSize: 9, color: '#EF4444', fontFamily: 'Inter-Bold' },
  helpChip: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, borderWidth: 1,
    backgroundColor: 'rgba(255,255,255,0.03)', alignSelf: 'flex-start', marginBottom: 8,
  },
  helpText: { fontSize: 11, fontFamily: 'Inter-Regular', flexShrink: 1 },
  log: { padding: 10, borderRadius: 10, borderWidth: 1, backgroundColor: 'rgba(0,0,0,0.2)', marginTop: 12 },
  logTitle: { fontSize: 11, fontFamily: 'Inter-Bold', letterSpacing: 1, marginBottom: 4 },
  logRow: { fontSize: 12, fontFamily: 'Inter-Regular', paddingVertical: 1 },
  toast: {
    position: 'absolute', top: 100, alignSelf: 'center',
    paddingHorizontal: 22, paddingVertical: 12, borderRadius: 999,
    elevation: 8, shadowColor: '#000', shadowOpacity: 0.4, shadowRadius: 8, zIndex: 100,
  },
  toastText: { color: '#fff', fontSize: 14, fontFamily: 'Inter-Black', letterSpacing: 0.5 },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.85)', alignItems: 'center', justifyContent: 'center' },
  modalCard: {
    padding: 28, borderRadius: 20, alignItems: 'center', borderWidth: 2,
    minWidth: 280, maxWidth: '85%',
  },
  modalEmoji: { fontSize: 56, marginBottom: 8 },
  modalTitle: { color: '#fff', fontSize: 24, fontFamily: 'Inter-Black', letterSpacing: 0.5 },
  modalSub: { fontSize: 13, fontFamily: 'Inter-SemiBold', marginTop: 4 },
  modalBtn: { paddingHorizontal: 22, paddingVertical: 12, borderRadius: 12 },
  modalBtnText: { color: '#fff', fontSize: 14, fontFamily: 'Inter-Bold' },
});

// Hook : online sync via Socket.IO /game (best-effort, doesn't block UI)
function useGameSocket(roomCode: string | undefined, onState: (s: any) => void) {
  const socketRef = useRef<Socket | null>(null);
  const [connected, setConnected] = useState(false);
  useEffect(() => {
    if (!roomCode) return;
    const s = io(`${SOCKET_URL}/game`, { transports: ['websocket'], timeout: 4000 });
    socketRef.current = s;
    s.on('connect', () => {
      setConnected(true);
      log.bin(`socket /game connected → join room:${roomCode}`);
      s.emit('game:join', { roomCode });
    });
    s.on('game:state', (snapshot: any) => {
      log.bout('game:state received', { phase: snapshot?.phase });
      onState(snapshot);
    });
    s.on('disconnect', () => setConnected(false));
    s.on('connect_error', (e: any) => log.warn('socket connect_error', e?.message));
    return () => { s.disconnect(); socketRef.current = null; };
  }, [roomCode]);
  const emitMove = useCallback((action: any) => {
    socketRef.current?.emit('game:action', { roomCode, action });
  }, [roomCode]);
  return { connected, emitMove };
}

const HELP_TEXT = "Posez des questions oui/non pour éliminer les candidats. Devinez la carte secrète.";
const FEEDBACK_SPECIAL = "🎯 Trouvé !";

export default function GameScreen() {
  const { roomCode } = useLocalSearchParams<{ roomCode: string }>();
  const router = useRouter();
  const { t } = useTranslation();
  const { palette } = useTheme();

  const [state, dispatch] = useReducer(Engine.gameReducer as any, undefined, () =>
    (Engine as any).createInitialState(true)
  );

  const [moveLog, setMoveLog] = useState<any[]>([]);
  const [toast, setToast] = useState<any>(null);
  const [showQuit, setShowQuit] = useState(false);
  // Quiestce state shape: { phase, players: [PlayerState, PlayerState], currentPlayerIndex, allCards, winnerId }
  const me = state.players?.[0];
  const opponent = state.players?.[1];
  const eliminated: Set<string> = me?.eliminatedCardIds ?? new Set();
  const candidates = (state.allCards ?? []).filter((c: any) => !eliminated.has(c.id));
  const secret = me?.secretCard;
  const winner = state.winnerId
    ? state.players?.find((p: any) => p.id === state.winnerId) ?? { name: state.winnerId }
    : null;

  const askSuit = (suit: any) => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light).catch(() => {});
    dispatch({ type: 'ASK_QUESTION', questionType: 'suit', value: suit } as any);
    setMoveLog(l => [...l, { icon: '❓', who: 'Vous', what: `couleur = ${suit} ?` }]);
  };
  const askValue = (value: number) => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light).catch(() => {});
    dispatch({ type: 'ASK_QUESTION', questionType: 'value_eq', value } as any);
    setMoveLog(l => [...l, { icon: '❓', who: 'Vous', what: `valeur = ${value} ?` }]);
  };
  const askIsFace = () => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light).catch(() => {});
    dispatch({ type: 'ASK_QUESTION', questionType: 'is_face' } as any);
    setMoveLog(l => [...l, { icon: '❓', who: 'Vous', what: 'figure ?' }]);
  };
  const guess = (cardId: string) => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy).catch(() => {});
    dispatch({ type: 'GUESS_CARD', cardId } as any);
    setMoveLog(l => [...l, { icon: '🎯', who: 'Vous', what: 'devine' }]);
  };

  useEffect(() => {
    if (winner) {
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success).catch(() => {});
      setToast({ msg: FEEDBACK_SPECIAL, color: '#10B981', key: Date.now() });
    }
  }, [winner]);

  const restart = () => {
    dispatch({ type: 'RESET' } as any);
    setMoveLog([]);
  };

  return (
    <View style={[localStyles.root, { backgroundColor: palette.bg }]}>
      <LinearGradient colors={palette.bgGradient} style={StyleSheet.absoluteFill} />
      <AppHeader title={APP_CONFIG.name} subtitle={`Salon ${roomCode ?? '—'}`} showBack onBack={() => setShowQuit(true)} />

      <ScrollView contentContainerStyle={localStyles.body}>
        <PhaseBanner phase={state.phase} current={null} isMyTurn={!winner} winner={winner} palette={palette} />
        <HelpChip palette={palette} text={HELP_TEXT} />

        {/* Secret card */}
        <LinearGradient colors={['rgba(249,115,22,0.18)', palette.card]} style={[localStyles.secretBox, { borderColor: APP_CONFIG.primary }]}>
          <Text style={[localStyles.label, { color: palette.textSecondary }]}>VOTRE SECRET</Text>
          {secret ? (
            <AnimatedCard value={String(secret.value)} suit={secret.suit} width={70} height={100} facing="up" />
          ) : (
            <Text style={{ color: palette.textSecondary }}>—</Text>
          )}
        </LinearGradient>

        {/* Quick ask */}
        <Text style={[localStyles.handTitle, { color: palette.text }]}>❓ Demander une couleur</Text>
        <View style={localStyles.askRow}>
          {['oros', 'copas', 'espadas', 'bastos'].map(s => (
            <TouchableOpacity key={s} style={[localStyles.askBtn, { backgroundColor: APP_CONFIG.primary }]} onPress={() => askSuit(s as any)}>
              <Text style={localStyles.askText}>{s.toUpperCase()}</Text>
            </TouchableOpacity>
          ))}
        </View>
        <Text style={[localStyles.handTitle, { color: palette.text, marginTop: 12 }]}>❓ Demander une valeur</Text>
        <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8 }}>
          {[1, 2, 3, 4, 5, 6, 7, 10, 11, 12].map(v => (
            <TouchableOpacity key={v} style={[localStyles.askBtnSmall, { backgroundColor: APP_CONFIG.secondary }]} onPress={() => askValue(v)}>
              <Text style={localStyles.askText}>{v}</Text>
            </TouchableOpacity>
          ))}
        </ScrollView>

        <TouchableOpacity style={[localStyles.askBtnFull, { backgroundColor: APP_CONFIG.secondary }]} onPress={askIsFace}>
          <Text style={localStyles.askText}>👤 Est-ce une figure ?</Text>
        </TouchableOpacity>

        <MoveLog entries={moveLog} palette={palette} />

        <Text style={[localStyles.handTitle, { color: palette.text, marginTop: 16 }]}>
          🎯 Candidats restants ({candidates.length})
        </Text>
        <View style={localStyles.candidatesGrid}>
          {candidates.map((c: any) => (
            <Pressable key={c.id} onPress={() => guess(c.id)} style={({ pressed }) => [{ transform: [{ scale: pressed ? 0.95 : 1 }] }]}>
              <AnimatedCard value={String(c.value)} suit={c.suit} width={50} height={72} facing="up" />
            </Pressable>
          ))}
        </View>
      </ScrollView>

      <FeedbackToast message={toast?.msg} visible={!!toast} color={toast?.color} key={toast?.key} />
      <WinnerModal visible={!!winner} winner={winner} onAgain={restart} onQuit={() => router.back()} palette={palette} />

      <Modal visible={showQuit} transparent animationType="fade">
        <View style={styles.modalBackdrop}>
          <View style={[styles.modalCard, { backgroundColor: palette.card, borderColor: palette.border }]}>
            <Text style={styles.modalTitle}>Quitter ?</Text>
            <View style={{ flexDirection: 'row', gap: 12, marginTop: 18 }}>
              <TouchableOpacity onPress={() => setShowQuit(false)} style={[styles.modalBtn, { backgroundColor: 'rgba(255,255,255,0.15)' }]}><Text style={styles.modalBtnText}>Annuler</Text></TouchableOpacity>
              <TouchableOpacity onPress={() => { setShowQuit(false); router.back(); }} style={[styles.modalBtn, { backgroundColor: '#EF4444' }]}><Text style={styles.modalBtnText}>Quitter</Text></TouchableOpacity>
            </View>
          </View>
        </View>
      </Modal>
    </View>
  );
}

const localStyles = StyleSheet.create({
  root: { flex: 1 },
  body: { padding: 14, paddingBottom: 40 },
  secretBox: { padding: 14, borderRadius: 14, borderWidth: 2, alignItems: 'center', marginBottom: 12 },
  label: { fontSize: 11, fontFamily: 'Inter-Bold', letterSpacing: 1, marginBottom: 8 },
  handTitle: { fontSize: 13, fontFamily: 'Inter-Bold', marginBottom: 8 },
  askRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  askBtn: { flex: 1, paddingVertical: 12, borderRadius: 10, alignItems: 'center', minWidth: 64 },
  askBtnSmall: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 8, alignItems: 'center' },
  askBtnFull: { padding: 14, borderRadius: 10, alignItems: 'center', marginTop: 10 },
  askText: { color: '#fff', fontSize: 13, fontFamily: 'Inter-Bold' },
  candidatesGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, justifyContent: 'center' },
});
